### ISSUE TITLE
PAN Summary Dataset

### ISSUE THREAD

**Issue by peermohtaram** [AVBelyy/normplagdet#1]
Where can I find the PAN Summary Dataset discussed in the paper?

**Comment by AVBelyy** [comment]
PAN Summary Dataset is a subset of a shared task named Text Alignment organized by PAN. We used 2013 and 2014 versions of it:
https://pan.webis.de/clef13/pan13-web/text-alignment.html
https://pan.webis.de/clef14/pan14-web/text-alignment.html

It appears you need to request access to get the dataset (was not the case when we were working on the paper), but if the data is unchanged, the Summary part annotations should be available under the "05-summary-obfuscation" folder.
