### ISSUE TITLE
Plagiarism Detection System

### ISSUE THREAD

**Issue by pangtongs** [AVBelyy/normplagdet#2]
Hi, I wanted to know how to get the plagiarism detection code mentioned in the paper such as
`Brlek et al`, `Le et al.` , and `Vani and Gupta`?

I understand that Sanchez-Perez et al. can be found at https://www.gelbukh.com/plagiarism-detection/PAN-2015/

**Comment by AVBelyy** [comment]
Hi Winston, I believe that for all papers you mentioned we were not able to find open sourced code either, so we requested the respective authors via email. At the time of publication, I believe we only obtained code from Brlek et al, so we were able to run it with our proposed metric.

**Comment by pangtongs** [comment]
Thank you very much for the response
